on:
  pull_request:
  push:
    branches:
      - master

name: CI

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - run: cargo fmt --all --check -- --config=imports_granularity=Crate
      - run: cargo clippy --all-targets --workspace -- -D warnings
      - run: cargo test --all-targets --workspace
